// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', './views/vouchers', './views/users'], function(angular, vouchersModule, usersModule) {
    return angular.module('dependencies', ['ngRoute', vouchersModule.name, usersModule.name]);
  });

}).call(this);

/*
//@ sourceMappingURL=dependencies.map
*/
