// Generated by CoffeeScript 1.6.3
(function() {
  define(['bower_components/angular/angular', './views/vouchers', './views/users'], function(angular, vouchersModule, usersModule) {
    var module;
    module = angular.module('dependencies', ['ngRoute', vouchersModule.name, usersModule.name]);
    return {
      moduleName: module.name
    };
  });

}).call(this);

/*
//@ sourceMappingURL=dependencies.map
*/
