// Generated by CoffeeScript 1.7.1
(function() {
  var __slice = [].slice;

  define(['angular', './services', './views/vouchers', './views/users'], function() {
    var modules, ng;
    ng = arguments[0], modules = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return ng.module('dependencies', modules.map(function(_) {
      return _.name;
    }));
  });

}).call(this);

//# sourceMappingURL=dependencies.map
