// Generated by CoffeeScript 1.7.1
(function() {
  define(['angular'], function(ng) {
    return ng.module('services', []).service('toQ', [
      '$q', function($q) {
        return function(func) {
          return $q.when(func());
        };
      }
    ]);
  });

}).call(this);

//# sourceMappingURL=services.map
