// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, restApi, webDir;

  express = require('express');

  restApi = require('./lib/rest_api');

  webDir = __dirname + '/web';

  app = express();

  restApi(app);

  app.use(express.bodyParser());

  app.use(express.directory(webDir));

  app.use(express["static"](webDir));

  app.listen(8666);

}).call(this);

/*
//@ sourceMappingURL=cashpoint.map
*/
