// Generated by CoffeeScript 1.6.3
(function() {
  define(['bower_components/angular/angular'], function(angular) {
    var module;
    module = angular.module('users', []);
    module.controller('UsersController', ['$scope', function($scope) {}]);
    return module;
  });

}).call(this);

/*
//@ sourceMappingURL=users.map
*/
