// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular'], function(angular) {
    var module;
    module = angular.module('users', []);
    module.controller('UsersController', [
      '$scope', 'Users', function($scope, usersService) {
        $scope.users = [];
        $scope.newUserName = null;
        usersService.updateUsers($scope);
        $scope.deleteUser = function(user) {
          return usersService.deleteUser($scope, user);
        };
        return $scope.addNewUser = function() {
          var user;
          if ($scope.newUserName) {
            user = {
              name: $scope.newUserName
            };
            $scope.newUserName = null;
            return usersService.addUser($scope, user);
          }
        };
      }
    ]);
    module.service('Users', [
      'usersDb', function(usersDb) {
        var fetchUsers, obj, options;
        options = {
          include_docs: true
        };
        fetchUsers = function() {
          return usersDb.allDocs(options).then(function(resp) {
            if (resp.total_rows) {
              return resp.rows;
            }
            return usersDb.bulkDocs({
              docs: [
                {
                  name: 'Alex'
                }, {
                  name: 'Katja'
                }
              ]
            }).then(function() {
              return usersDb.allDocs(options);
            }).then(function(resp) {
              return resp.rows;
            });
          });
        };
        return obj = {
          updateUsers: function(scope) {
            return fetchUsers().then(function(rows) {
              return scope.$apply(function() {
                return scope.users = rows.map(function(row) {
                  return row.doc;
                });
              });
            });
          },
          deleteUser: function(scope, user) {
            usersDb.remove(user);
            return obj.updateUsers(scope);
          },
          addUser: function(scope, user) {
            return usersDb.post(user).then(function() {
              return obj.updateUsers(scope);
            });
          }
        };
      }
    ]);
    return module;
  });

}).call(this);

/*
//@ sourceMappingURL=users.map
*/
