// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular'], function(angular) {
    var module;
    module = angular.module('vouchers', []);
    module.controller('VouchersController', ['$scope', 'vouchersDb', function($scope, vouchersDb) {}]);
    return module;
  });

}).call(this);

/*
//@ sourceMappingURL=vouchers.map
*/
