// Generated by CoffeeScript 1.7.1
(function() {
  define(['angular', 'moment'], function(ng, moment) {
    var module;
    module = ng.module('vouchers', []);
    module.controller('VouchersController', [
      '$scope', 'vouchers', function($scope, vouchersService) {
        $scope.vouchers = [];
        $scope.users = [];
        $scope.newVoucher = {
          paidAt: moment().format('YYYY-MM-DD')
        };
        vouchersService.updateUsersInScope($scope);
        vouchersService.updateVouchersInScope($scope);
        $scope.addVoucher = function() {
          console.log($scope.newVoucher);
          if ($scope.newVoucher && $scope.newVoucher.amount) {
            $scope.newVoucher.repaid = false;
            $scope.newVoucher.repaidAt = null;
            vouchersService.addVoucher($scope, ng.copy($scope.newVoucher))["catch"](function(e) {
              return console.error(e);
            });
            return $scope.newVoucher = {
              paidAt: new Date()
            };
          }
        };
        return $scope.deleteVoucher = function(voucher) {
          return vouchersService.deleteVoucher($scope, voucher);
        };
      }
    ]);
    module.service('vouchers', [
      'toQ', 'usersDb', 'vouchersDb', function(toQ, usersDb, vouchersDb) {
        var fetchUsers, fetchVouchers, obj, options;
        options = {
          include_docs: true
        };
        fetchUsers = function() {
          return usersDb.allDocs(options).then(function(_) {
            return _.rows || [];
          });
        };
        fetchVouchers = function() {
          return vouchersDb.allDocs(options).then(function(_) {
            return _.rows || [];
          });
        };
        return obj = {
          updateUsersInScope: function(scope) {
            return fetchUsers().then(function(rows) {
              return scope.$apply(function() {
                return scope.users = rows.map(function(_) {
                  return _.doc;
                });
              });
            });
          },
          updateVouchersInScope: function(scope) {
            return fetchVouchers().then(function(rows) {
              return scope.$apply(function() {
                return scope.vouchers = rows.map(function(_) {
                  return _.doc;
                });
              });
            });
          },
          deleteVoucher: function(scope, voucher) {
            vouchersDb.remove(voucher);
            return obj.updateVouchersInScope(scope);
          },
          addVoucher: function(scope, voucher) {
            return toQ(function() {
              return vouchersDb.post(voucher).then(function() {
                return obj.updateVouchersInScope(scope);
              });
            });
          },
          repayVoucher: function(scope, voucher) {
            voucher.repaid = true;
            return toQ(function() {
              return usersDb.put(voucher).then(function() {
                return obj.updateVouchersInScope(scope);
              });
            });
          }
        };
      }
    ]);
    return module;
  });

}).call(this);

//# sourceMappingURL=vouchers.map
