// Generated by CoffeeScript 1.6.3
(function() {
  define({
    usersDbName: 'http://myDbHost:5984/users',
    vouchersDbName: 'http://myDbHost:5984/vouchers'
  });

}).call(this);

/*
//@ sourceMappingURL=config.example.map
*/
