// Generated by CoffeeScript 1.7.1
(function() {
  require.config({
    shim: {
      angular: {
        exports: 'angular'
      },
      'angular-route': {
        deps: ['angular']
      },
      bootstrap: {
        deps: ['jquery']
      }
    },
    paths: {
      angular: 'bower_components/angular/angular',
      'angular-route': 'bower_components/angular-route/angular-route',
      bootstrap: 'bower_components/bootstrap/dist/js/bootstrap.min',
      jquery: 'bower_components/jquery/dist/jquery.min',
      moment: 'bower_components/momentjs/moment',
      pouchdb: 'bower_components/pouchdb/dist/pouchdb-nightly'
    }
  });

  require(['angular', 'angular-route', 'pouchdb', 'lib/dependencies', 'config', 'bootstrap'], function(ng, ngRoute, PouchDB, dependencies, config, unused) {
    var module, routes;
    routes = [
      {
        path: '/vouchers',
        templateUrl: 'lib/views/vouchers.html',
        controller: 'VouchersController',
        title: 'Kassenzettelübersicht'
      }, {
        path: '/users',
        templateUrl: 'lib/views/users.html',
        controller: 'UsersController',
        title: 'Benutzer'
      }
    ];
    module = ng.module('main', [dependencies.name, 'ngRoute']);
    module.config([
      '$routeProvider', function($routeProvider) {
        routes.forEach(function(route) {
          return $routeProvider.when(route.path, {
            templateUrl: route.templateUrl,
            controller: route.controller
          });
        });
        return $routeProvider.otherwise({
          redirectTo: routes[0].path
        });
      }
    ]);
    module.controller('ApplicationController', [
      '$scope', '$location', function($scope, $location) {
        $scope.routes = routes;
        return $scope.isActiveRoute = function(route) {
          return $location.path() === route.path;
        };
      }
    ]);
    module.service('usersDb', function() {
      return new PouchDB(config.usersDbName);
    });
    module.service('vouchersDb', function() {
      return new PouchDB(config.vouchersDbName);
    });
    return ng.element(document).ready(function() {
      return ng.bootstrap(document, ['main']);
    });
  });

}).call(this);

//# sourceMappingURL=index.map
