// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    shim: {
      'bower_components/angular/angular': {
        exports: 'angular'
      }
    }
  });

  require(['bower_components/angular/angular', 'lib/dependencies'], function(angular, dependencies) {
    return require(['bower_components/angular-route/angular-route'], function() {
      var module, routes;
      routes = [
        {
          path: '/vouchers',
          templateUrl: 'lib/views/vouchers.html',
          controller: 'VouchersController',
          title: 'Kassenzettelübersicht'
        }, {
          path: '/users',
          templateUrl: 'lib/views/users.html',
          controller: 'UsersController',
          title: 'Benutzer'
        }
      ];
      module = angular.module('main', [dependencies.moduleName, 'ngRoute']);
      module.config([
        '$routeProvider', '$locationProvider', function($routeProvider, $locationProvider) {
          routes.forEach(function(route) {
            return $routeProvider.when(route.path, {
              templateUrl: route.templateUrl,
              controller: route.controller
            });
          });
          return $routeProvider.otherwise({
            redirectTo: routes[0].path
          });
        }
      ]);
      module.controller('ApplicationController', [
        '$scope', '$location', function($scope, $location) {
          $scope.routes = routes;
          return $scope.isActiveRoute = function(route) {
            return $location.path() === route.path;
          };
        }
      ]);
      return angular.element(document).ready(function() {
        return angular.bootstrap(document, ['main']);
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
