// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    paths: {
      angular: 'bower_components/angular/angular',
      'angular-route': 'bower_components/angular-route/angular-route',
      pouchdb: 'bower_components/pouchdb/dist/pouchdb-nightly'
    },
    shim: {
      angular: {
        exports: 'angular'
      },
      'angular-route': {
        deps: ['angular']
      }
    }
  });

  require(['angular', 'angular-route', 'pouchdb', 'lib/dependencies', 'config'], function(angular, angularRoute, PouchDB, dependencies, config) {
    var module, routes;
    routes = [
      {
        path: '/vouchers',
        templateUrl: 'lib/views/vouchers.html',
        controller: 'VouchersController',
        title: 'Kassenzettelübersicht'
      }, {
        path: '/users',
        templateUrl: 'lib/views/users.html',
        controller: 'UsersController',
        title: 'Benutzer'
      }
    ];
    module = angular.module('main', [dependencies.name, 'ngRoute']);
    module.config([
      '$routeProvider', '$locationProvider', function($routeProvider, $locationProvider) {
        routes.forEach(function(route) {
          return $routeProvider.when(route.path, {
            templateUrl: route.templateUrl,
            controller: route.controller
          });
        });
        return $routeProvider.otherwise({
          redirectTo: routes[0].path
        });
      }
    ]);
    module.controller('ApplicationController', [
      '$scope', '$location', function($scope, $location) {
        $scope.routes = routes;
        return $scope.isActiveRoute = function(route) {
          return $location.path() === route.path;
        };
      }
    ]);
    module.service('usersDb', function() {
      return new PouchDB(config.usersDbName);
    });
    module.service('vouchersDb', function() {
      return new PouchDB(config.vouchersDbName);
    });
    return angular.element(document).ready(function() {
      return angular.bootstrap(document, ['main']);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
